### PR TITLE
[TSK-748] migration(ui-kit):fix UserAvatar

### LINKED ISSUE #81: [TSK-748] ui-kit: fix UserAvatar
As proposed by @ObitoDevv , to update the UserAvatar in the mainbranch so it can be shared across all open PRs. In the future, as soon as you notice that a small component is shared across more than one task, please open a PR for that shared component so we can merge it first.

@carlapbg and I will go through all open and merged components to do a similar comment. So, everytime there's an image URL, and the image doesn't work, we shouldn't see things like this:

Image

To handle this properly: (i) the component should check if the URL works, only render the image if it does; (ii) if the URL doesnt work (or its empty), then in this case, get the two first letters of the first two words of the name, and show them as initials

### PR DESCRIPTION
**Pull request by jatinrise**
## Description

- Component name: 'UserAvatar`
- Figma link or screenshot: [Figma Design](https://www.figma.com/)

Screenshot 2025-03-17 at 11 31 24

## Checklist

- [x] I have run the lint, build, and test commands locally, as explained in the README, before creating this PR to ensure the code is clean and functional.
- [x] My changes align with the **core models** that have been discussed and agreed upon.
- [x] The component design has been compared to the **Figma design** to ensure consistency.
- [x] The **component is fully responsive** and behaves as expected across different screen sizes.
- [x] The component **supports keyboard web accessibility** (if applicable).
- [x] I have written **unit tests** or **integration tests** to cover the component's functionality above the coverage threshold.
- [x] I have updated the **documentation** for the component, including usage examples and guidelines.
- [x] I have **commented** my code, particularly in complex or non-obvious areas.
- [x] The **component is properly exported** for use in other parts of the application.

---

## Related Issues

Fixes #81

### CODE REVIEW

File: packages/ui-kit/lib/components/avatar/user-avatar.tsx [hunk 1]
```diff
@@ -1,62 +1,69 @@
...
 
-export interface UserAvatarProps {
-  size?: 'xSmall' | 'small' | 'medium' | 'large' | 'xLarge'; // Defines avatar sizes
-  hasProfilePicture?: boolean; // Indicates if the user has a profile picture
-  imageUrl?: string; // URL of the profile picture
-  initials?: string; // Initials to display if no profile picture is present
-  className?: string; // Additional styling classes
+export interface UserAvatarWithPicture {
+  size?: 'xSmall' | 'small' | 'medium' | 'large' | 'xLarge';
+  hasProfilePicture?: true | false;
```
Comment (alebg) [inline packages/ui-kit/lib/components/avatar/user-avatar.tsx:6]: unnecessary prop, it's not being used

File: packages/ui-kit/lib/components/avatar/user-avatar.tsx [hunk 2]
```diff
@@ -1,62 +1,69 @@
...
+  imageUrl?: string;
+  initials?: string;
```
Comment (alebg) [inline packages/ui-kit/lib/components/avatar/user-avatar.tsx:8]: please pass the full name of the user, and do the computation of the initials here

**Comment by alebg** [comment]
> Just one small thing, in the section "with profile picture" in storybook using Safari, the bottom part on the avatar cuts a little bit:
> 
> Screenshot 2025-03-17 at 12 42 00

@carlapbg please keep it in your notes. For now we'll give it a pass since it's only affecting your Mac / Safari. We'll take a deeper look later if it's still a problem

**Review by alebg — APPROVED** [review]
Thanks, great job @jatinrise !

**Review by carlapbg — APPROVED** [review]
The avatar still cuts at the bottom on Safari. For now we will let it pass.

Screenshot 2025-03-17 at 14 46 36
